FROM ubuntu:latest

# 设置工作目录为 /app
WORKDIR /app

# 复制当前目录下的所有文件到容器中的 /app 目录
COPY hello.py .

# 将归档文件 "archive.tar.gz" 解压到容器中的 "/app/data" 目录下
ADD archive.tar.gz data/

# 执行一些命令，例如在 /app 目录下创建一个文件
RUN touch example.txt

# 在容器中执行命令时，默认将相对于 /app 目录
CMD ls -l